const ccnaData = {
   modules: [
        { id: "dhcp", title: "DHCP & DNS", icon: "🔄", status: "Attivo" },
        { id: "ospf", title: "OSPF Routing", icon: "🛣️", status: "Attivo" },
        { id: "vlan", title: "VLAN & Trunking", icon: "🏗️", status: "Attivo" },
        { id: "stp",  title: "Spanning Tree", icon: "🌲", status: "Attivo" },
        { id: "security", title: "Security Fund.", icon: "🛡️", status: "Attivo" },
        { id: "ipv6", title: "IPv6 Addressing", icon: "🌐", status: "Attivo" }    
    ],

    questions: {
        dhcp: [
            // --- DOMANDE DA 1 A 15 ---
            { q: "Quale porta UDP usa il Server DHCP?", a: ["67", "68", "53", "161"], c: 0, f: "Il server ascolta sulla porta 67, il client sulla 68." },
            { q: "Cosa significa l'acronimo DORA?", a: ["Discover, Offer, Request, Ack", "Data, Open, Route, Access", "Direct, Over, Real, Active", "Dynamic, Open, Remote, Area"], c: 0, f: "Rappresenta le 4 fasi dello scambio messaggi DHCP." },
            { q: "Quale comando mostra i conflitti di indirizzi IP su un router Cisco?", a: ["show ip dhcp conflict", "show ip dhcp binding", "show ip dhcp pool", "debug dhcp"], c: 0, f: "Mostra gli IP che il router ha rilevato come già in uso." },
            { q: "In quale stato si trova il client quando invia un DHCP Request?", a: ["Selecting", "Requesting", "Init", "Bound"], c: 1, f: "Il client richiede formalmente l'offerta ricevuta nel pacchetto Offer." },
            { q: "L'indirizzo 169.254.x.x indica l'uso di:", a: ["APIPA", "DHCP Relay", "Static IP", "Loopback"], c: 0, f: "APIPA viene usato quando il client non riceve risposta dal DHCP." },
            { q: "Quale tipo di record DNS mappa un nome a un indirizzo IPv6?", a: ["A", "AAAA", "CNAME", "MX"], c: 1, f: "Il record AAAA (quad-A) è specifico per IPv6." },
            { q: "Cosa fa il comando 'ip helper-address'?", a: ["Inoltra broadcast DHCP come unicast", "Configura il DNS", "Crea una VLAN", "Attiva il routing"], c: 0, f: "Permette ai messaggi DHCP di attraversare i router." },
            { q: "Un record CNAME serve a:", a: ["Creare un alias per un nome esistente", "Mappare un IP", "Gestire le mail", "Indicare l'autorità"], c: 0, f: "CNAME sta per Canonical Name." },
            { q: "Il comando 'ip dhcp excluded-address' serve a:", a: ["Riservare IP per uso statico", "Cancellare il pool", "Bloccare il DNS", "Spegnere il servizio"], c: 0, f: "Evita che il DHCP assegni IP già assegnati a server o stampanti." },
            { q: "Quale porta usa il protocollo DNS?", a: ["53", "67", "80", "443"], c: 0, f: "DNS usa sia UDP che TCP sulla porta 53." },
            { q: "DHCP Discover viene inviato come:", a: ["Broadcast", "Unicast", "Multicast", "Anycast"], c: 0, f: "Il client non ha ancora un IP, quindi 'urla' in broadcast." },
            { q: "Il tempo di lease predefinito in IOS Cisco è:", a: ["24 ore", "1 ora", "7 giorni", "Infinite"], c: 0, f: "Il valore standard è un giorno intero." },
            { q: "Cosa contiene il messaggio DHCP Offer?", a: ["Proposta di indirizzo IP e opzioni", "Richiesta di conferma", "Messaggio di errore", "Conferma finale"], c: 0, f: "Il server propone un IP al client." },
            { q: "Quale comando crea un pool DHCP chiamato 'CLIENTS'?", a: ["ip dhcp pool CLIENTS", "network dhcp pool CLIENTS", "service dhcp CLIENTS", "set dhcp CLIENTS"], c: 0, f: "È il primo comando per configurare il servizio." },
            { q: "DNS: cosa significa FQDN?", a: ["Fully Qualified Domain Name", "Fast Query Data Network", "File Queue Domain Name", "Fixed Quality Domain Network"], c: 0, f: "È il nome completo del dominio, incluso l'host." },

            // --- DOMANDE DA 16 A 30 ---
            { q: "Quale tipo di record DNS serve a localizzare i server di posta?", a: ["MX", "A", "PTR", "NS"], c: 0, f: "MX sta per Mail Exchanger." },
            { q: "Se un client riceve più DHCP Offer, quale sceglie?", a: ["La prima che arriva", "L'IP più basso", "L'IP più alto", "Quella con più opzioni"], c: 0, f: "Il client accetta solitamente la prima offerta ricevuta." },
            { q: "La porta UDP usata dal Client DHCP per trasmettere è:", a: ["68", "67", "53", "69"], c: 0, f: "Il client trasmette dalla porta 68 verso la 67 del server." },
            { q: "Cos'è il TTL in un record DNS?", a: ["Time To Live (tempo di cache)", "Total Traffic Limit", "Type Tag Length", "Top Tier Level"], c: 0, f: "Indica per quanti secondi il record può essere cachato prima di rieseguire la query." },
            { q: "Quale messaggio DHCP usa il client per rilasciare l'IP?", a: ["DHCP Release", "DHCP Decline", "DHCP Cancel", "DHCP NAK"], c: 0, f: "Comunica al server che l'IP è di nuovo disponibile." },
            { q: "Cosa significa query DNS ricorsiva?", a: ["Il server risolve il nome per conto del client", "Il client chiede a più server", "La query fallisce", "Si usa solo per IPv6"], c: 0, f: "Il server DNS si assume l'onere di trovare la risposta finale." },
            { q: "Quale record DNS viene usato per il Reverse Lookup (da IP a Nome)?", a: ["PTR", "AAAA", "NS", "SOA"], c: 0, f: "Pointer record (PTR) mappa l'IP al nome host." },
            { q: "Come si chiama l'attacco in cui si esauriscono tutti gli IP del DHCP?", a: ["DHCP Starvation", "DHCP Spoofing", "MAC Flooding", "SYN Flood"], c: 0, f: "L'attaccante richiede IP all'infinito usando MAC finti." },
            { q: "La funzione 'DHCP Snooping' serve a:", a: ["Bloccare server DHCP abusivi", "Spiare le password", "Velocizzare il DNS", "Fare il routing"], c: 0, f: "Isola i messaggi DHCP provenienti da porte non fidate." },
            { q: "Quale opzione DHCP serve a indicare l'IP del server TFTP (es. per telefoni VoIP)?", a: ["Opzione 150", "Opzione 43", "Opzione 6", "Opzione 3"], c: 0, f: "Opzione 150 fornisce l'IP del server TFTP." },
            { q: "In DHCPv6, quale messaggio sostituisce il DHCP Discover?", a: ["Solicit", "Advertise", "Request", "Hello"], c: 0, f: "In IPv6 il processo inizia con un messaggio di Solicit." },
            { q: "Quale comando permette di vedere le statistiche di ricezione/invio DHCP?", a: ["show ip dhcp server statistics", "show dhcp stats", "show ip dhcp pool", "show ip route"], c: 0, f: "Mostra il conteggio dettagliato dei messaggi DORA." },
            { q: "Cosa fa un client se rileva che l'IP offerto dal DHCP è già in uso?", a: ["Invia un DHCP Decline", "Invia un DHCP Release", "Si spegne", "Accetta comunque"], c: 0, f: "Invia un Decline e ricomincia il processo DORA." },
            { q: "Quale livello della gerarchia DNS gestisce i domini .com, .org, .it?", a: ["TLD (Top-Level Domain)", "Root", "Authoritative", "Second-Level"], c: 0, f: "Sono i domini di primo livello." },
            { q: "Il file HOSTS locale viene consultato:", a: ["Prima del server DNS", "Dopo il server DNS", "Solo se il DNS fallisce", "Mai"], c: 0, f: "I sistemi operativi controllano prima il file HOSTS locale." },

            // --- DOMANDE DA 31 A 45 ---
            { q: "In DHCPv6, il messaggio 'Advertise' corrisponde a:", a: ["DHCP Offer", "DHCP Discover", "DHCP Request", "DHCP Ack"], c: 0, f: "È la risposta del server al messaggio di Solicit." },
            { q: "Perché il DHCP Request viene inviato in broadcast?", a: ["Per avvisare gli altri server che l'offerta è stata accettata", "Perché non sa dove sia il server", "Perché lo switch lo richiede", "Perché è più veloce"], c: 0, f: "Informa gli altri server DHCP che possono liberare gli IP che avevano proposto." },
            { q: "Un record DNS di tipo NS indica:", a: ["I Name Server autoritativi per la zona", "L'indirizzo IPv4", "Il server di posta", "L'IP del gateway"], c: 0, f: "Indica quali server gestiscono quel dominio." },
            { q: "In DHCP, cosa succede se il client riceve un DHCP NAK?", a: ["Deve ricominciare il processo DORA", "Accetta l'IP comunque", "Invia un pacchetto Release", "Usa un IP statico"], c: 0, f: "Negative Acknowledgment: il server rifiuta la richiesta e si ricomincia." },
            { q: "Quale comando IOS esclude gli IP da 192.168.1.1 a 192.168.1.10?", a: ["ip dhcp excluded-address 192.168.1.1 192.168.1.10", "exclude 192.168.1.1 192.168.1.10", "dhcp exclude 192.168.1.1 192.168.1.10", "no dhcp pool 192.168.1.1"], c: 0, f: "Il comando accetta un range specificando IP iniziale e finale." },
            { q: "DHCP Snooping classifica le porte dello switch in:", a: ["Trusted e Untrusted", "Active e Passive", "Root e Designated", "Trunk e Access"], c: 0, f: "Le porte verso i server DHCP legittimi devono essere impostate come Trusted." },
            { q: "Cosa significa SLAAC in ambito IPv6?", a: ["Stateless Address Auto Configuration", "Static Local Address Auto Control", "Stateful Large Address Allocation", "Simple Line Address Access"], c: 0, f: "Permette a un host IPv6 di auto-configurarsi senza un server DHCPv6." },
            { q: "Il DNS dinamico (DDNS) serve a:", a: ["Aggiornare automaticamente i record DNS quando l'IP cambia", "Cambiare la porta del DNS", "Velocizzare le query", "Criptare il traffico"], c: 0, f: "Associa gli IP dinamici assegnati dal DHCP a nomi di dominio fissi." },
            { q: "L'opzione DHCP 43 viene usata per:", a: ["Fornire l'IP del Wireless LAN Controller (WLC)", "Impostare il DNS", "Definire la subnet mask", "Assegnare il gateway"], c: 0, f: "Fornisce informazioni specifiche del vendor (come i WLC Cisco)." },
            { q: "Un server DNS autoritativo è quello che:", a: ["Possiede i record originali di una determinata zona", "Fa solo da cache", "Inoltra le richieste", "Blocca i siti web"], c: 0, f: "È il server responsabile finale per quel dominio specifico." },
            { q: "Cosa contiene il record DNS SOA (Start of Authority)?", a: ["Informazioni amministrative e timer della zona", "L'IP del server di posta", "L'alias del nome", "Nessuna delle precedenti"], c: 0, f: "Contiene dati vitali come il seriale di zona e i tempi di refresh." },
            { q: "In quale scenario l'ip helper-address è indispensabile?", a: ["Quando client e server DHCP sono in subnet diverse", "Sempre", "Solo per IPv6", "Solo se si usa OSPF"], c: 0, f: "Un router non inoltra i broadcast. L'helper-address li converte in unicast." },
            { q: "L'attacco 'DNS Spoofing' (o Cache Poisoning) consiste nel:", a: ["Inserire dati falsi nella cache del server DNS", "Spegnere il server DNS", "Rubare gli IP del pool", "Monitorare il traffico"], c: 0, f: "Indirizza gli utenti verso siti maligni falsificando le risposte DNS." },
            { q: "Nel comando 'network 192.168.1.0 255.255.255.0' del DHCP Cisco, cosa si definisce?", a: ["Il range di indirizzi da assegnare", "L'IP del router", "Il server DNS", "La porta di ascolto"], c: 0, f: "Definisce la subnet da cui il pool pescherà gli indirizzi." },
            { q: "Cosa succede quando il tempo di lease di un IP arriva al 50%?", a: ["Il client invia un DHCP Request per rinnovarlo", "Il client rilascia l'IP", "L'IP scade immediatamente", "Viene eseguito un reboot"], c: 0, f: "Il client entra in fase di rinnovo (T1) e contatta il server originale." },

            // --- DOMANDE DA 46 A 60 ---
            { q: "Quale messaggio ICMPv6 usa un host in SLAAC per chiedere i dati di rete al router?", a: ["Router Solicitation (RS)", "Router Advertisement (RA)", "Neighbor Solicit", "Echo Request"], c: 0, f: "L'host invia un RS per sollecitare una risposta immediata dal router." },
            { q: "Il messaggio Router Advertisement (RA) in IPv6 viene inviato:", a: ["Periodicamente dai router", "Solo se richiesto", "Mai", "Solo dai PC"], c: 0, f: "I router inviano RA periodicamente per informare gli host sulla rete." },
            { q: "In DHCPv6 Stateful, chi assegna gli indirizzi IP?", a: ["Il server DHCPv6", "Il router tramite RA", "L'host stesso", "Nessuno"], c: 0, f: "Lo Stateful funziona esattamente come il DHCP classico in IPv4." },
            { q: "Un record DNS TXT viene spesso usato per:", a: ["Sistemi anti-spam (SPF, DKIM)", "Mappare gli IP", "I server di posta", "Il reverse lookup"], c: 0, f: "Contiene testo arbitrario leggibile dalle macchine per la sicurezza del dominio." },
            { q: "Cosa fa il comando 'dns-server 8.8.8.8' all'interno di un pool DHCP Cisco?", a: ["Comunica ai client quale server DNS usare", "Trasforma il router in un server DNS", "Configura il DNS del router", "Blocca il DNS di Google"], c: 0, f: "Passa l'indirizzo del DNS primario ai client che richiedono l'IP." },
            { q: "La porta usata dal client DHCPv6 è la:", a: ["546", "547", "67", "68"], c: 0, f: "In IPv6 le porte cambiano: 546 per il client e 547 per il server." },
            { q: "Che tipo di indirizzo usa il comando ip helper-address come destinazione?", a: ["Un indirizzo Unicast", "Un indirizzo Broadcast", "Un indirizzo Multicast", "Un indirizzo Anycast"], c: 0, f: "Trasforma il broadcast originale del client in un pacchetto unicast verso il server." },
            { q: "Nella risoluzione DNS iterativa, se un server non conosce la risposta:", a: ["Fornisce l'IP di un altro server a cui chiedere", "Risponde con un errore", "Cerca lui la risposta", "Spegne la connessione"], c: 0, f: "Rimanda il client a un server più autorevole." },
            { q: "Cosa succede se si assegna un IP statico a un PC all'interno del pool DHCP senza escluderlo?", a: ["Si rischia un conflitto di IP", "Il DHCP lo riconosce e non lo usa", "Il PC si disconnette", "Tutto funziona senza problemi"], c: 0, f: "Il DHCP potrebbe assegnare quell'IP a un altro PC creando un conflitto." },
            { q: "Il comando 'default-router 192.168.1.254' in un pool DHCP Cisco serve a:", a: ["Assegnare il Gateway predefinito ai client", "Impostare l'IP del router", "Attivare OSPF", "Nessuna delle precedenti"], c: 0, f: "Dice ai client quale IP usare per uscire dalla propria subnet." },
            { q: "Che cos'è l'EUI-64 usato talvolta in SLAAC?", a: ["Un metodo per creare l'ID interfaccia IPv6 usando il MAC address", "Un protocollo di crittografia", "Un tipo di switch", "Il nome di un router"], c: 0, f: "Prende il MAC a 48 bit e inserisce FFFE in mezzo per arrivare a 64 bit." },
            { q: "Cosa succede quando scade il tempo di lease completo di un IP?", a: ["Il client deve smettere di usare l'IP e rinegoziare", "Il client continua a usarlo", "Il server si spegne", "Viene assegnato lo stesso IP"], c: 0, f: "Se non rinnovato entro il limite, l'IP torna libero nel pool." },
            { q: "I server DNS Root si trovano:", a: ["Al vertice della gerarchia DNS", "In fondo alla gerarchia", "Solo in Europa", "Dentro i router aziendali"], c: 0, f: "Ci sono 13 indirizzi IP logici per i root server che gestiscono il mondo." },
            { q: "Quale comando permette di vedere gli IP attualmente assegnati dal DHCP Cisco?", a: ["show ip dhcp binding", "show ip dhcp pool", "show ip route", "show running-config"], c: 0, f: "Mostra la tabella che lega l'IP assegnato al MAC address del client." },
            { q: "Se un PC è impostato per ottenere l'IP automaticamente ma non c'è un server DHCP attivo:", a: ["Si auto-assegna un IP APIPA (169.254.x.x)", "Non ha nessun IP", "Prende l'IP 0.0.0.0", "Usa l'IP del vicino"], c: 0, f: "I sistemi Windows e Mac usano APIPA per comunicare almeno nella LAN locale." }
        ],
        ospf: [
            // --- DA 1 A 15 ---
            { q: "Qual è la Distanza Amministrativa di OSPF?", a: ["110", "90", "120", "1"], c: 0, f: "OSPF ha AD 110." },
            { q: "Algoritmo usato da OSPF?", a: ["SPF (Dijkstra)", "DUAL", "Bellman-Ford", "STP"], c: 0, f: "Shortest Path First calcola l'albero dei percorsi minimi." },
            { q: "Quale comando attiva OSPF con ID processo 10?", a: ["router ospf 10", "network ospf 10", "ip ospf process 10", "routing ospf 10"], c: 0, f: "Il numero del processo è locale al router." },
            { q: "Area obbligatoria in una rete multi-area?", a: ["Area 0", "Area 1", "Area 100", "Area backbone 1"], c: 0, f: "Tutte le aree devono connettersi all'Area 0." },
            { q: "Come calcola il costo OSPF per default?", a: ["100 Mbps / larghezza di banda", "Numero di hop", "Ritardo del link", "MTU"], c: 0, f: "Formula: Reference Bandwidth / Interface Bandwidth." },
            { q: "Indirizzo Multicast per AllSPFRouters?", a: ["224.0.0.5", "224.0.0.6", "224.0.0.9", "224.0.0.10"], c: 0, f: "Tutti i router OSPF ascoltano sul 224.0.0.5." },
            { q: "Stato finale di adiacenza tra due router in una rete point-to-point?", a: ["FULL", "2-WAY", "EXCHANGE", "LOADING"], c: 0, f: "Lo stato FULL indica sincronizzazione completa." },
            { q: "Quale router ha la priorità più alta nell'elezione DR?", a: ["Quello con il valore priority più alto", "Quello col MAC più basso", "Quello col RID più basso", "Quello più vecchio"], c: 0, f: "Default priority è 1, il valore più alto vince." },
            { q: "Cosa indica il Router ID (RID)?", a: ["Nome univoco del router nel dominio OSPF", "Indirizzo IP del gateway", "Numero del processo", "Versione di OSPF"], c: 0, f: "Indispensabile per identificare chi ha generato un LSA." },
            { q: "Comando per rendere un'interfaccia passiva?", a: ["passive-interface <nome>", "no ospf interface", "shutdown ospf", "isolate interface"], c: 0, f: "Smette di inviare Hello ma include la subnet negli update." },
            { q: "OSPF Hello Timer predefinito su Ethernet?", a: ["10 secondi", "30 secondi", "5 secondi", "60 secondi"], c: 0, f: "Sulle reti broadcast è 10 secondi." },
            { q: "Quale LSA descrive i router all'interno di un'area?", a: ["Tipo 1", "Tipo 2", "Tipo 3", "Tipo 5"], c: 0, f: "LSA Tipo 1 (Router LSA) è generato da ogni router." },
            { q: "Un router ABR è:", a: ["Un router tra due aree", "Un router interno", "Il router centrale", "Un router con una sola area"], c: 0, f: "Area Border Router connette un'area all'Area 0." },
            { q: "Cosa succede se il Dead Timer scade?", a: ["L'adiacenza viene rimossa", "Il router riavvia", "Cambia il RID", "Non succede nulla"], c: 0, f: "Il router viene considerato morto e rimosso dalla topologia." },
            { q: "Comando per vedere i vicini OSPF?", a: ["show ip ospf neighbor", "show ip route ospf", "show ospf neighbors", "show ip ospf database"], c: 0, f: "Fondamentale per il troubleshooting delle adiacenze." },

            // --- DA 16 A 30 ---
            { q: "Qual è la priorità di default di un'interfaccia OSPF?", a: ["1", "0", "64", "255"], c: 0, f: "Il valore di default è 1. Se impostata a 0, il router non parteciperà all'elezione DR/BDR." },
            { q: "In quale stato i router decidono chi sarà Master e chi Slave?", a: ["ExStart", "Exchange", "Init", "Loading"], c: 0, f: "In ExStart viene determinato l'ordine di scambio dei database." },
            { q: "L'indirizzo Multicast 224.0.0.6 è usato da:", a: ["DR e BDR", "Tutti i router OSPF", "Solo il Root Bridge", "Nessuno"], c: 0, f: "I router non-DR inviano i loro update solo a DR e BDR su questo indirizzo." },
            { q: "Quale comando cambia la Reference Bandwidth di OSPF?", a: ["auto-cost reference-bandwidth", "ip ospf cost", "bandwidth", "ospf speed"], c: 0, f: "Necessario per link moderni oltre i 100Mbps." },
            { q: "Cosa significa LSA?", a: ["Link State Advertisement", "Link Static Address", "Local State Access", "Log System Alert"], c: 0, f: "È il pacchetto di informazioni topologiche inviato dai router." },
            { q: "Quale tipo di LSA è usato per annunciare rotte esterne?", a: ["Tipo 5", "Tipo 3", "Tipo 2", "Tipo 1"], c: 0, f: "AS External LSA (Tipo 5) trasporta rotte esterne al dominio OSPF." },
            { q: "Un router ASBR è:", a: ["Un router che connette OSPF a un altro protocollo", "Un router di backup", "Un router nell'area 0", "Un router senza vicini"], c: 0, f: "Autonomous System Boundary Router." },
            { q: "Quale comando mostra il contenuto del Link State Database?", a: ["show ip ospf database", "show ip route", "show ip ospf interface", "show ip ospf neighbor"], c: 0, f: "Mostra tutti gli LSA ricevuti dal router." },
            { q: "In una rete Point-to-Point, chi viene eletto come DR?", a: ["Nessuno", "Il router col RID più alto", "Il router più vecchio", "Entrambi"], c: 0, f: "Sulle reti point-to-point non avviene l'elezione DR/BDR." },
            { q: "Cosa succede se due router OSPF hanno lo stesso Router ID?", a: ["L'adiacenza non si forma", "Si fondono", "Funziona tutto", "Il secondo router esplode"], c: 0, f: "Il RID deve essere univoco in tutto il dominio OSPF." },
            { q: "Quale stato indica che un router ha ricevuto un Hello ma non il proprio RID?", a: ["Init", "2-Way", "Attempt", "Down"], c: 0, f: "Init significa comunicazione unidirezionale." },
            { q: "Cosa fa il comando 'default-information originate'?", a: ["Annuncia una rotta di default", "Resetta il router", "Cambia il RID", "Mostra l'IP"], c: 0, f: "Propaga la rotta 0.0.0.0/0 agli altri router OSPF." },
            { q: "Qual è il valore di default del Dead Timer rispetto all'Hello Timer?", a: ["4 volte l'Hello Timer", "2 volte", "10 volte", "Sono uguali"], c: 0, f: "Default: 10s Hello, 40s Dead." },
            { q: "Quale comando imposta manualmente il RID?", a: ["router-id <indirizzo>", "id router <indirizzo>", "ip ospf rid", "set rid"], c: 0, f: "Va dato dentro il processo 'router ospf'." },
            { q: "Il costo di un link GigabitEthernet (1000 Mbps) di default è:", a: ["1", "10", "100", "19"], c: 0, f: "Poiché la ref-bw è 100M, ogni link >= 100M ha costo 1." },

            // --- DA 31 A 45 ---
            { q: "In OSPF, l'LSA Tipo 2 (Network LSA) è generato da:", a: ["Il Designated Router (DR)", "Ogni router", "L'ABR", "L'ASBR"], c: 0, f: "Il DR descrive tutti i router connessi allo stesso segmento multi-access." },
            { q: "Quale comando permette di attivare OSPF direttamente su un'interfaccia?", a: ["ip ospf 10 area 0", "router ospf 10", "network 0.0.0.0", "ospf enable"], c: 0, f: "È il metodo moderno alternativo al comando network." },
            { q: "Cosa si intende per 'ospf area mismatch'?", a: ["Configurazione di aree diverse su link adiacenti", "Process ID diverso", "RID uguale", "MTU diversa"], c: 0, f: "I router non formeranno adiacenza se l'area non coincide." },
            { q: "In una rete Broadcast, cosa succede se il DR cade?", a: ["Il BDR diventa DR immediatamente", "Si rifà l'elezione da zero", "La rete si ferma", "Il router col RID più basso vince"], c: 0, f: "Il BDR è pronto a subentrare senza ritardi." },
            { q: "Il messaggio OSPF LSU (Link State Update) contiene:", a: ["Uno o più LSA", "Solo Hello", "Richieste di IP", "Coordinate GPS"], c: 0, f: "LSU è il contenitore usato per inviare le informazioni topologiche." },
            { q: "In OSPFv3, il supporto è per:", a: ["IPv6", "Solo IPv4", "Solo AppleTalk", "IPX"], c: 0, f: "OSPFv3 è stato riscritto principalmente per gestire IPv6." },
            { q: "Qual è il valore massimo della metrica (costo) in OSPF?", a: ["65535", "255", "15", "Illimitato"], c: 0, f: "Il costo è un valore a 16 bit." },
            { q: "Cosa succede se l'MTU non corrisponde tra due vicini OSPF?", a: ["L'adiacenza resta bloccata in EXCHANGE", "Funziona ma è lento", "Il router crasha", "Ignora il problema"], c: 0, f: "Il mismatch dell'MTU impedisce lo scambio del database." },
            { q: "Quale comando mostra se un'interfaccia è DR, BDR o DRother?", a: ["show ip ospf interface", "show ip ospf neighbor", "show ip route", "show version"], c: 0, f: "Fornisce i dettagli sul ruolo dell'interfaccia." },
            { q: "OSPF è un protocollo di tipo:", a: ["Link State", "Distance Vector", "Path Vector", "Statico"], c: 0, f: "Mantiene una mappa completa (topologia) della rete." },
            { q: "Un'area OSPF chiamata 'Stub' non accetta:", a: ["LSA Tipo 5 (esterne)", "Hello", "LSA Tipo 1", "Rotte interne"], c: 0, f: "Le aree Stub ignorano le rotte esterne per risparmiare memoria." },
            { q: "Il pacchetto DBD (Database Description) contiene:", a: ["Un riassunto degli LSA posseduti", "Tutti i dati della rete", "Solo password", "Richieste di aiuto"], c: 0, f: "Usato per confrontare i database tra vicini." },
            { q: "Quale comando permette di vedere il tempo trascorso dall'ultima adiacenza?", a: ["show ip ospf neighbor", "show ip ospf", "show version", "uptime ospf"], c: 0, f: "Mostra da quanto tempo i router sono vicini." },
            { q: "Cosa indica lo stato '2-WAY'?", a: ["I router si vedono ma non scambiano database", "Sincronizzazione completa", "Errore critico", "Il link è spento"], c: 0, f: "Tipico tra due router DRother." },
            { q: "In OSPF, cosa definisce la wildcard mask nel comando network?", a: ["La porzione di indirizzo IP da controllare", "Il costo", "L'ID del processo", "La priorità"], c: 0, f: "0 significa 'deve coincidere', 255 significa 'ignora'." },

            // --- DA 46 A 60 ---
            { q: "Quale tipo di LSA è usato per descrivere la rotta verso un ASBR?", a: ["Tipo 4", "Tipo 1", "Tipo 2", "Tipo 3"], c: 0, f: "ASBR Summary LSA (Tipo 4) indica dove si trova l'ASBR." },
            { q: "L'LSA Tipo 3 (Summary LSA) è generato da:", a: ["ABR", "ASBR", "DR", "Ogni router"], c: 0, f: "Annuncia le rotte di un'area alle altre aree." },
            { q: "OSPF usa il protocollo IP numero:", a: ["89", "88", "17", "6"], c: 0, f: "OSPF gira direttamente sopra IP (protocol 89)." },
            { q: "Il processo di elezione DR/BDR avviene in quale stato?", a: ["2-Way", "Init", "Exchange", "Full"], c: 0, f: "L'elezione deve finire prima dello scambio dati." },
            { q: "Cosa indica un costo OSPF pari a 1?", a: ["Link veloce (FastEthernet o superiore)", "Link lento", "Rotta statica", "Errore"], c: 0, f: "Con ref-bw di 100M, 1 è il costo minimo." },
            { q: "Quale comando mostra quanti LSA ci sono nel database?", a: ["show ip ospf database", "show ip ospf stats", "show ip ospf lsa", "show running-config"], c: 0, f: "Elenca il numero di Router LSA, Network LSA, ecc." },
            { q: "In un'area Totally Stubby, cosa si riceve per andare fuori?", a: ["Solo una rotta di default", "Tutte le rotte", "Nulla", "Solo rotte Tipo 3"], c: 0, f: "Blocca LSA 3, 4 e 5 lasciando solo la default." },
            { q: "Cosa succede se il RID non viene configurato manualmente?", a: ["Usa l'IP più alto delle loopback", "Non parte", "Prende 0.0.0.0", "Usa il MAC"], c: 0, f: "Cerca Loopback, poi le interfacce fisiche attive." },
            { q: "Quale comando permette di debuggare le adiacenze?", a: ["debug ip ospf adj", "debug ip ospf packet", "show ip ospf neighbor", "debug ospf hello"], c: 0, f: "Mostra gli stati (Init, ExStart, ecc.) in tempo reale." },
            { q: "Il messaggio LSAck serve a:", a: ["Confermare la ricezione di un LSU", "Salutare i vicini", "Richiedere un IP", "Chiudere la connessione"], c: 0, f: "OSPF richiede conferme per ogni update." },
            { q: "Sulle interfacce seriali Frame Relay (NBMA), l'Hello timer è:", a: ["30 secondi", "10 secondi", "5 secondi", "60 secondi"], c: 0, f: "Sulle reti non-broadcast è più lento (30s)." },
            { q: "Cosa indica lo stato 'LOADING'?", a: ["Il router richiede LSA mancanti", "Il router sta riavviando", "Il database è pieno", "C'è un loop"], c: 0, f: "Il router scarica i dettagli tramite LSR." },
            { q: "In OSPF, cosa si intende per 'Convergence'?", a: ["Tutti i router hanno la stessa visione della rete", "Il router è spento", "I cavi sono collegati", "La password è corretta"], c: 0, f: "Stato in cui il routing è stabile." },
            { q: "Qual è la wildcard mask per la subnet 255.255.255.252?", a: ["0.0.0.3", "0.0.0.255", "0.0.3.255", "255.255.255.0"], c: 0, f: "Sottrai la mask da 255.255.255.255." },
            { q: "Perché usare una Loopback per il RID?", a: ["Perché non va mai giù (always UP)", "Perché è più veloce", "Perché è sicura", "Perché usa meno RAM"], c: 0, f: "Garantisce stabilità al processo OSPF." }
        ],
       vlan: [
            // --- DA 1 A 15 ---
            { q: "Protocollo di trunking standard IEEE?", a: ["802.1Q", "ISL", "802.3ad", "802.11"], c: 0, f: "802.1Q è lo standard universale per il tagging VLAN." },
            { q: "Quanti bit ha l'identificatore VLAN (VID)?", a: ["12 bit", "8 bit", "16 bit", "4 bit"], c: 0, f: "Con 12 bit si possono avere fino a 4096 VLAN." },
            { q: "Range delle VLAN normali?", a: ["1 - 1005", "1 - 4094", "100 - 500", "0 - 1024"], c: 0, f: "Il range esteso arriva fino a 4094, ma il normale fino a 1005." },
            { q: "Comando per creare la VLAN 10?", a: ["vlan 10", "create vlan 10", "set vlan 10", "interface vlan 10"], c: 0, f: "Si usa in modalità di configurazione globale." },
            { q: "Una porta in modalità 'access' può:", a: ["Appartenere a una sola VLAN", "Gestire il trunk", "Inviare tag 802.1Q", "Avere più IP"], c: 0, f: "Le porte access collegano gli host finali a una sola VLAN." },
            { q: "La Native VLAN serve a:", a: ["Gestire il traffico senza tag", "Criptare i dati", "Spegnere lo switch", "Routing"], c: 0, f: "Il traffico sulla Native VLAN attraversa il trunk non taggato." },
            { q: "Cosa succede se c'è un mismatch della Native VLAN?", a: ["Possibili loop e traffico incrociato", "Lo switch esplode", "Tutto funziona", "Si spegne il trunk"], c: 0, f: "È un errore di configurazione segnalato dal protocollo CDP." },
            { q: "Router-on-a-Stick usa:", a: ["Subinterfaces logiche", "Molti cavi fisici", "Switch L3", "Solo hub"], c: 0, f: "Usa un'unica interfaccia fisica divisa in sotto-interfacce per il routing tra VLAN." },
            { q: "Comando per assegnare una porta alla VLAN 20?", a: ["switchport access vlan 20", "vlan 20 member", "port vlan 20", "assign vlan 20"], c: 0, f: "Comando fondamentale da dare sotto l'interfaccia." },
            { q: "Voice VLAN serve a:", a: ["Isolare il traffico VoIP", "Sentire la musica", "Amplificare il segnale", "Gestire i trunk"], c: 0, f: "Separa i dati PC dalla voce per applicare politiche di QoS." },
            { q: "VTP (VLAN Trunking Protocol) serve a:", a: ["Sincronizzare le VLAN tra switch", "Creare trunk", "Routing", "Sicurezza"], c: 0, f: "Propaga la creazione/cancellazione di VLAN in un dominio switch." },
            { q: "Quale comando mostra lo stato dei trunk?", a: ["show interfaces trunk", "show vlan brief", "show ip trunk", "show running-config"], c: 0, f: "Mostra quali porte sono trunk, la modalità e la native vlan." },
            { q: "Il tag 802.1Q dove viene inserito?", a: ["Tra l'indirizzo Source e il Type", "Alla fine del frame", "Nel preambolo", "Nel payload"], c: 0, f: "Viene inserito nell'header Ethernet originale (4 byte)." },
            { q: "DTP (Dynamic Trunking Protocol) serve a:", a: ["Negoziare automaticamente un trunk", "Assegnare IP", "Sicurezza", "Backup"], c: 0, f: "Protocollo proprietario Cisco per l'auto-configurazione dei link tra switch." },
            { q: "Cosa fa 'switchport mode dynamic desirable'?", a: ["Tenta attivamente di diventare un trunk", "Resta in access", "Spegne la porta", "Usa solo ISL"], c: 0, f: "Invia pacchetti DTP per chiedere alla controparte di formare un trunk." },

            // --- DA 16 A 30 ---
            { q: "Qual è la VLAN di default su uno switch Cisco?", a: ["VLAN 1", "VLAN 0", "VLAN 100", "Nessuna"], c: 0, f: "Tutte le porte appartengono alla VLAN 1 per impostazione predefinita." },
            { q: "Perché è una buona pratica cambiare la Native VLAN?", a: ["Per motivi di sicurezza (VLAN hopping)", "Per velocizzare la rete", "Per risparmiare energia", "Non serve a nulla"], c: 0, f: "Evita che traffico non taggato possa essere iniettato in VLAN non autorizzate." },
            { q: "Cosa fa il comando 'switchport nonegotiate'?", a: ["Disabilita DTP sulla porta", "Forza il trunk", "Spegne la porta", "Attiva il routing"], c: 0, f: "Si usa quando l'altro lato non supporta DTP o per sicurezza." },
            { q: "In Router-on-a-stick, quale comando incapsula il traffico nella VLAN 10?", a: ["encapsulation dot1Q 10", "vlan 10 enable", "trunk 10", "ip vlan 10"], c: 0, f: "Va configurato sotto la sub-interface del router." },
            { q: "Una SVI (Switch Virtual Interface) serve a:", a: ["Fornire un gateway Layer 3 alle VLAN sullo switch", "Creare un trunk", "Fisicamente collegare un PC", "Nessuna delle precedenti"], c: 0, f: "È un'interfaccia logica (es: interface vlan 10) usata per il routing o il management." },
            { q: "Il comando 'show vlan brief' non mostra:", a: ["Le porte in modalità trunk", "Le porte access", "Il nome della VLAN", "Lo stato della VLAN"], c: 0, f: "Le porte trunk non appaiono in questo comando, devi usare 'show interfaces trunk'." },
            { q: "Cos'è il 'VLAN Hopping'?", a: ["Un attacco per accedere a VLAN non autorizzate", "Un metodo di routing veloce", "Una funzione di STP", "Un comando Cisco"], c: 0, f: "Sfrutta le impostazioni di default dei trunk per scavalcare la segmentazione." },
            { q: "Quale modalità DTP non invia messaggi di negoziazione?", a: ["Access / Static Trunk", "Dynamic Auto", "Dynamic Desirable", "Tutte"], c: 0, f: "Le modalità statiche non negoziano se configurate con nonegotiate." },
            { q: "Quante VLAN può gestire il protocollo ISL (Cisco)?", a: ["1000", "4096", "2048", "12"], c: 0, f: "ISL supporta meno VLAN rispetto allo standard 802.1Q." },
            { q: "Cosa succede se cancelli una VLAN che ha ancora porte assegnate?", a: ["Le porte diventano inattive (non passano traffico)", "Tornano in VLAN 1", "Si spegne lo switch", "Funzionano lo stesso"], c: 0, f: "Le porte restano assegnate a una VLAN che non esiste più e smettono di funzionare." },
            { q: "In VTP, quale modalità permette di creare/modificare VLAN?", a: ["Server", "Client", "Transparent", "Off"], c: 0, f: "Il Server è l'unico che può modificare il database VLAN nel dominio." },
            { q: "VTP Transparent cosa fa con gli update ricevuti?", a: ["Li inoltra agli altri ma non li applica", "Li ignora totalmente", "Li sovrascrive", "Li applica solo a sé stesso"], c: 0, f: "Non partecipa alla sincronizzazione ma fa passare i pacchetti VTP." },
            { q: "Il comando 'switchport trunk allowed vlan 10,20' serve a:", a: ["Limitare il traffico trunk solo a quelle VLAN", "Creare le VLAN 10 e 20", "Spegne le altre VLAN", "Assegnare le porte"], c: 0, f: "È fondamentale per la sicurezza e l'efficienza: evita broadcast inutili." },
            { q: "Qual è la funzione del comando 'switchport mode dynamic auto'?", a: ["Diventa trunk solo se l'altro lato lo richiede", "Forza il trunk", "Tenta sempre di diventare trunk", "Spegne la porta"], c: 0, f: "È la modalità passiva di DTP." },
            { q: "Il comando 'no switchport' su uno switch Layer 3 serve a:", a: ["Trasformare una porta switch in una porta routed", "Disabilitare la porta", "Creare un trunk", "Attiva STP"], c: 0, f: "Permette di assegnare un indirizzo IP direttamente all'interfaccia fisica." },

            // --- DA 31 A 45 ---
            { q: "Cosa si intende per 'Extended Range' VLAN?", a: ["VLAN da 1006 a 4094", "VLAN da 1 a 1005", "VLAN per il WiFi", "VLAN di management"], c: 0, f: "Vengono usate principalmente dai Service Provider." },
            { q: "In quale file vengono salvate le VLAN normali (1-1005)?", a: ["vlan.dat", "running-config", "startup-config", "vlan.txt"], c: 0, f: "Le VLAN sono salvate nella memoria Flash nel file vlan.dat." },
            { q: "Cosa indica il comando 'switchport trunk native vlan 99'?", a: ["Imposta la VLAN 99 come quella non taggata sul trunk", "Spegne la VLAN 99", "Assegna tutti i PC alla VLAN 99", "Cripta la VLAN 99"], c: 0, f: "Cambia la native VLAN predefinita (che è la 1)." },
            { q: "Per abilitare il routing tra VLAN su uno switch L3, quale comando serve?", a: ["ip routing", "routing enable", "vlan routing", "ipv4 routing"], c: 0, f: "Senza questo comando globale, lo switch si comporta come un semplice Layer 2." },
            { q: "Cos'è un 'Collision Domain' in una VLAN?", a: ["Ogni singola porta dello switch", "Tutta la VLAN", "Tutto lo switch", "Solo il trunk"], c: 0, f: "Sui moderni switch full-duplex, ogni porta è un dominio di collisione separato." },
            { q: "Quale tipo di traffico non viene mai taggato in 802.1Q?", a: ["Traffico della Native VLAN", "Traffico voce", "Traffico management", "Traffico dati"], c: 0, f: "La Native VLAN è definita proprio come la VLAN senza tag sul trunk." },
            { q: "Quanti tag 802.1Q può avere al massimo un frame? (Q-in-Q)", a: ["Due", "Uno", "Illimitati", "Sedici"], c: 0, f: "Il Double Tagging (Q-in-Q) è usato dai provider per tunnel Layer 2." },
            { q: "Cosa succede se due switch hanno password VTP diverse?", a: ["Non sincronizzano il database VLAN", "Lo switch si blocca", "Funziona tutto", "Si resettano"], c: 0, f: "La password deve coincidere per accettare gli update." },
            { q: "In Router-on-a-stick, il gateway per i PC della VLAN 10 è:", a: ["L'indirizzo IP della sub-interface del router", "L'IP dello switch", "L'IP del server DNS", "L'IP del primo PC"], c: 0, f: "Il router funge da gateway per tutte le VLAN." },
            { q: "Quale comando permette di vedere le informazioni VTP?", a: ["show vtp status", "show vlan vtp", "show status vtp", "show run vtp"], c: 0, f: "Mostra la versione, il nome dominio e la modalità." },
            { q: "Cosa significa 'VLAN Pruning'?", a: ["Rimuovere traffico broadcast inutile dai trunk", "Cancellare VLAN", "Tagliare i cavi", "Limitare gli accessi"], c: 0, f: "Ottimizza la banda evitando di inviare traffico per VLAN che non esistono sullo switch di destinazione." },
            { q: "Il comando 'name SALES' sotto 'vlan 10' serve a:", a: ["Assegnare un nome descrittivo alla VLAN", "Creare un utente", "Assegnare una password", "Non esiste"], c: 0, f: "Serve per l'organizzazione amministrativa della rete." },
            { q: "Se un PC in VLAN 10 non pinga un PC in VLAN 20, il problema è probabilmente:", a: ["Manca un dispositivo di routing (Router o Switch L3)", "Manca il trunk", "Cavo rotto", "La porta è in access"], c: 0, f: "Dispositivi in VLAN diverse non possono comunicare senza routing (Layer 3)." },
            { q: "Quale protocollo usa DTP per trasportare i suoi frame?", a: ["Layer 2 (Cisco proprietario)", "TCP", "UDP", "ICMP"], c: 0, f: "DTP è un protocollo di puro Layer 2." },
            { q: "VTP Revision Number aumenta ogni volta che:", a: ["Viene modificata una VLAN", "Si riavvia lo switch", "Cambia l'IP", "Sempre"], c: 0, f: "Lo switch con il Revision Number più alto vince e propaga le modifiche." },

            // --- DA 46 A 60 ---
            { q: "Un attacco di 'Double Tagging' sfrutta:", a: ["La Native VLAN", "Il router", "Il server DHCP", "Le password"], c: 0, f: "L'attaccante mette due tag per far inoltrare il pacchetto dal trunk a una seconda VLAN." },
            { q: "Cosa succede se colleghi due switch con Native VLAN diverse?", a: ["Errore 'Native VLAN mismatch' e possibile leak di dati", "Tutto normale", "Il trunk non sale", "Lo switch si spegne"], c: 0, f: "È un grave errore di sicurezza e stabilità monitorato da CDP." },
            { q: "Le VLAN estese (1006-4094) richiedono VTP in modalità:", a: ["Transparent (o VTP v3)", "Server", "Client", "Non funzionano"], c: 0, f: "VTP v1 e v2 non supportano le VLAN estese." },
            { q: "Qual è la dimensione massima di un frame Ethernet con il tag 802.1Q?", a: ["1522 byte", "1500 byte", "1518 byte", "2000 byte"], c: 0, f: "Si aggiungono 4 byte ai 1518 byte standard." },
            { q: "Il comando 'switchport trunk encapsulation dot1q' è necessario su:", a: ["Switch che supportano sia ISL che 802.1Q", "Tutti gli switch", "Nessuno switch", "Solo sui router"], c: 0, f: "Alcuni switch datati richiedono di specificare il tipo di incapsulamento prima di attivare il trunk." },
            { q: "Cosa fa il comando 'vtp domain CISCO'?", a: ["Imposta il nome del dominio VTP", "Crea una VLAN chiamata CISCO", "Assegna una password", "Non fa nulla"], c: 0, f: "Tutti gli switch devono avere lo stesso dominio per sincronizzarsi." },
            { q: "In uno switch L3, la SVI viene creata con il comando:", a: ["interface vlan <id>", "vlan interface <id>", "logical vlan <id>", "ip vlan <id>"], c: 0, f: "Es: interface vlan 10." },
            { q: "Quale comando permette di vedere l'indirizzo MAC di un PC in una specifica VLAN?", a: ["show mac address-table vlan <id>", "show vlan mac", "show ip arp", "show mac brief"], c: 0, f: "Filtra la tabella dei MAC per la VLAN scelta." },
            { q: "Una porta 'Dynamic Auto' collegata a un'altra 'Dynamic Auto' diventa:", a: ["Access", "Trunk", "Spenta", "Loop"], c: 0, f: "Nessuna delle due prende l'iniziativa, quindi rimangono porte access." },
            { q: "Il 'Voice VLAN ID' viene comunicato al telefono tramite:", a: ["CDP o LLDP", "DHCP", "DNS", "Segnali acustici"], c: 0, f: "Lo switch dice al telefono su quale VLAN inviare la voce." },
            { q: "Qual è il vantaggio principale delle VLAN?", a: ["Riduzione dei domini di broadcast", "Aumento della velocità dei cavi", "Eliminazione del router", "Aumento della RAM"], c: 0, f: "Isola il traffico broadcast migliorando prestazioni e sicurezza." },
            { q: "Cosa indica lo stato 'Active' in 'show vlan brief'?", a: ["La VLAN è operativa sullo switch", "La VLAN sta inviando dati", "La VLAN è un trunk", "La VLAN è sotto attacco"], c: 0, f: "Indica che la VLAN è stata creata correttamente." },
            { q: "Si può avere un trunk su un cavo incrociato (crossover)?", a: ["Sì, non influisce", "No, serve cavo dritto", "Solo se lo switch è vecchio", "Solo se c'è un router"], c: 0, f: "Il tipo di cavo non influisce sul protocollo di trunking (specie con Auto-MDIX)." },
            { q: "Cosa succede se imposti una porta trunk come access?", a: ["Si perde la connettività per tutte le VLAN tranne una", "Funziona tutto", "Lo switch riavvia", "Il PC esplode"], c: 0, f: "La porta smetterà di accettare frame taggati." },
            { q: "Il comando 'default interface fa0/1' è utile per:", a: ["Resettare la configurazione della porta", "Attivare la porta", "Spegnerla", "Metterla in VLAN 1"], c: 0, f: "Rimuove tutte le configurazioni fatte (es: switchport, vlan, ecc.)." }
        ],
        stp: [
            // --- DA 1 A 15 ---
            { q: "Scopo principale di STP?", a: ["Evitare loop Layer 2", "Routing", "Assegnare IP", "Gestire password"], c: 0, f: "Blocca i percorsi ridondanti per evitare tempeste di broadcast." },
            { q: "Standard IEEE per lo Spanning Tree classico?", a: ["802.1D", "802.1w", "802.1Q", "802.1s"], c: 0, f: "L'originale è lo standard 802.1D." },
            { q: "Quale Bridge ID vince l'elezione a Root Bridge?", a: ["Il più basso", "Il più alto", "Il più veloce", "Quello con più porte"], c: 0, f: "La Priority più bassa vince. Se pari, vince il MAC più basso." },
            { q: "Valore di priorità STP predefinito su switch Cisco?", a: ["32768", "4096", "1", "65535"], c: 0, f: "Tutti gli switch Cisco partono con il valore 32768." },
            { q: "In quale stato STP la porta impara i MAC ma non inoltra dati?", a: ["Learning", "Listening", "Forwarding", "Blocking"], c: 0, f: "Stato intermedio per popolare la MAC table senza creare loop." },
            { q: "RSTP (Rapid STP) risponde allo standard:", a: ["802.1w", "802.1D", "802.1s", "802.1Q"], c: 0, f: "Introduce una convergenza molto più rapida rispetto al classico." },
            { q: "La funzione PortFast si applica a:", a: ["Porte collegate a host (PC)", "Trunk tra switch", "Solo router", "Server DHCP"], c: 0, f: "Porta l'interfaccia subito in Forwarding bypassando gli stati intermedi." },
            { q: "BPDU Guard spegne la porta se:", a: ["Riceve un BPDU", "Cade il link", "L'host si spegne", "C'è traffico"], c: 0, f: "Protegge le porte PortFast dall'attacco di switch non autorizzati." },
            { q: "Costo STP predefinito di un link 100 Mbps?", a: ["19", "4", "100", "2"], c: 0, f: "I costi standard IEEE sono: 10M=100, 100M=19, 1G=4." },
            { q: "Il Root Bridge ha tutte le porte in stato:", a: ["Designated", "Root", "Blocking", "Disabled"], c: 0, f: "Tutte le porte del Root Bridge sono in stato di inoltro (Designated)." },
            { q: "Una 'Alternate Port' in RSTP è:", a: ["Un backup della Root Port", "Una porta rotta", "Un trunk", "La porta principale"], c: 0, f: "Diventa immediatamente Root Port se quella principale cade." },
            { q: "Il timer 'Forward Delay' dura di default:", a: ["15 secondi", "2 secondi", "20 secondi", "50 secondi"], c: 0, f: "Tempo passato in Listening e poi in Learning (totale 30s)." },
            { q: "PVST+ (Cisco) permette di:", a: ["Avere un'istanza STP per ogni VLAN", "Velocizzare il trunk", "Criptare BPDU", "Spegnere STP"], c: 0, f: "Per-VLAN Spanning Tree permette il bilanciamento del carico." },
            { q: "Root Guard serve a:", a: ["Impedire che uno switch esterno diventi Root Bridge", "Proteggere il router", "Velocizzare STP", "Bloccare i PC"], c: 0, f: "Mette la porta in root-inconsistent se riceve BPDU superiori." },
            { q: "Qual è il Bridge ID tie-breaker se le priorità sono uguali?", a: ["MAC Address più basso", "IP più alto", "Numero seriale", "Velocità porte"], c: 0, f: "Il MAC address è l'identificatore univoco finale." },

            // --- DA 16 A 30 ---
            { q: "Le BPDU vengono inviate ogni (Hello Time):", a: ["2 secondi", "10 secondi", "30 secondi", "5 secondi"], c: 0, f: "È il valore di default per il battito cardiaco di STP." },
            { q: "Quale comando attiva il Rapid-PVST su Cisco?", a: ["spanning-tree mode rapid-pvst", "spanning-tree rapid enable", "switchport mode rapid", "stp mode rstp"], c: 0, f: "Configurazione globale per passare a RSTP." },
            { q: "Cosa succede se una porta in 'Blocking' smette di ricevere BPDU?", a: ["Passa a Listening dopo che Max Age è scaduto", "Si spegne", "Diventa Root subito", "Non succede nulla"], c: 0, f: "Attende la scadenza del timer (default 20s) prima di reagire." },
            { q: "Il valore 'Max Age' di default è:", a: ["20 secondi", "15 secondi", "2 secondi", "50 secondi"], c: 0, f: "Tempo massimo di conservazione delle info di una BPDU." },
            { q: "La porta di uno switch non-root con il percorso migliore verso il Root è:", a: ["Root Port", "Designated Port", "Backup Port", "Disabled"], c: 0, f: "Ogni switch non-root deve avere esattamente una Root Port." },
            { q: "In RSTP, lo stato 'Discarding' accorpa:", a: ["Disabled, Blocking, Listening", "Learning, Forwarding", "Solo Blocking", "Listening, Learning"], c: 0, f: "RSTP semplifica gli stati per velocizzare la logica." },
            { q: "Cosa fa 'spanning-tree vlan 10 priority 4096'?", a: ["Aumenta le probabilità che lo switch diventi Root", "Spegne la VLAN 10", "Imposta il costo a 4096", "Non è un comando valido"], c: 0, f: "Imposta una priorità più bassa del default (quindi più forte)." },
            { q: "L'incremento della priorità STP deve essere multiplo di:", a: ["4096", "1000", "2", "1024"], c: 0, f: "A causa dell'Extended System ID (VLAN ID a 12 bit)." },
            { q: "Cosa indica una porta in stato 'Broken' (Loop Guard)?", a: ["Errore di ricezione BPDU unidirezionale", "Cavo staccato", "Switch vecchio", "Porta in Forwarding"], c: 0, f: "Loop Guard evita loop causati da guasti ai link unidirezionali." },
            { q: "EtherChannel e STP:", a: ["STP vede l'EtherChannel come un unico link logico", "STP blocca tutte le porte tranne una", "Non funzionano insieme", "EtherChannel spegne STP"], c: 0, f: "L'aggregazione evita che STP blocchi i link ridondanti." },
            { q: "Quale pacchetto avvisa STP di un cambio di topologia?", a: ["TCN (Topology Change Notification)", "Hello", "LSU", "DORA"], c: 0, f: "I router avvisano il Root del cambiamento tramite TCN." },
            { q: "In RSTP, una porta collegata a un altro switch (full-duplex) è:", a: ["Point-to-point", "Edge port", "Shared port", "Root"], c: 0, f: "Definita in base al tipo di duplex." },
            { q: "In RSTP, una 'Edge Port' corrisponde a:", a: ["Una porta con PortFast attivo", "La Root Port", "Una porta rotta", "Un trunk"], c: 0, f: "Indica una porta collegata a un dispositivo finale." },
            { q: "Cosa fa il Root Bridge se riceve un TCN?", a: ["Invia una BPDU con il bit TC impostato", "Si riavvia", "Ignora il messaggio", "Cambia il proprio MAC"], c: 0, f: "Avvisa gli switch di ridurre il tempo di aging della MAC table." },
            { q: "Comando per vedere il Root Bridge per la VLAN 1?", a: ["show spanning-tree vlan 1", "show root", "show ip stp", "show running-config"], c: 0, f: "Mostra il Bridge ID del Root e i costi locali." },

            // --- DA 31 A 45 ---
            { q: "MST (Multiple Spanning Tree) standard:", a: ["802.1s", "802.1w", "802.1Q", "802.1D"], c: 0, f: "Permette di mappare più VLAN su una singola istanza STP." },
            { q: "Cosa fa 'UplinkFast'?", a: ["Accelera la transizione se la Root Port cade", "Velocizza il boot", "Aumenta la banda", "Spegne il trunk"], c: 0, f: "Funzione Cisco per switch di accesso con link ridondanti." },
            { q: "PortFast su un trunk tra switch cosa causa?", a: ["Rischio elevato di loop immediato", "Tutto funziona meglio", "Lo switch lo impedisce", "Non cambia nulla"], c: 0, f: "PortFast non deve MAI essere usato tra switch." },
            { q: "Il comando 'spanning-tree vlan 1 root primary' imposta la priority a:", a: ["24576", "4096", "0", "32768"], c: 0, f: "Imposta un valore significativamente più basso del default." },
            { q: "Quale stato RSTP corrisponde al 'Forwarding'?", a: ["Forwarding", "Learning", "Discarding", "Active"], c: 0, f: "Lo stato di inoltro dati finale." },
            { q: "La protezione 'BPDU Filter' cosa fa?", a: ["Smette di inviare e ricevere BPDU sulla porta", "Filtra solo le BPDU errate", "Cripta le BPDU", "Riavvia lo switch"], c: 0, f: "A differenza di BPDU Guard, non spegne la porta." },
            { q: "Cosa si intende per 'Root Path Cost'?", a: ["Somma dei costi dei link verso il Root Bridge", "Il costo di una singola porta", "La priorità del Root", "Il numero di hop"], c: 0, f: "Determina quale porta diventa la Root Port." },
            { q: "In ambiente multi-vendor si usa spesso:", a: ["MSTP o RSTP standard", "PVST+", "ISL", "VTP"], c: 0, f: "Per compatibilità tra Cisco e altri brand." },
            { q: "Cosa indica 'P2p' in show spanning-tree?", a: ["Link in modalità Full-Duplex", "Interfaccia rotta", "Interfaccia Half-Duplex", "Interfaccia host"], c: 0, f: "Indica un collegamento Point-to-Point." },
            { q: "Il comando 'spanning-tree vlan 1 root secondary' imposta la priority a:", a: ["28672", "24576", "32768", "4096"], c: 0, f: "Imposta lo switch come backup del Root primario." },
            { q: "Una 'Backup Port' in RSTP è:", a: ["Backup di una Designated Port sullo stesso segmento", "Backup della Root Port", "Una porta spenta", "Un trunk"], c: 0, f: "Capita solitamente se ci sono due link verso lo stesso Hub." },
            { q: "Cosa succede ai MAC Address dopo un Topology Change?", a: ["Vengono rimossi più velocemente (Aging a 15s)", "Cancellati tutti subito", "Salvati su flash", "Nulla"], c: 0, f: "Lo switch accelera la pulizia della tabella MAC." },
            { q: "L'Extended System ID contiene:", a: ["Il VLAN ID", "L'indirizzo IP", "Il seriale", "La versione"], c: 0, f: "Permette di identificare l'istanza per VLAN." },
            { q: "Costo STP di un link 10 Gbps?", a: ["2", "1", "19", "4"], c: 0, f: "Nuovo standard IEEE per link ad alta velocità." },
            { q: "Perché STP è critico in Layer 2?", a: ["I frame Ethernet non hanno un campo TTL", "È lento", "Consuma CPU", "Assegna IP"], c: 0, f: "Senza TTL, un loop farebbe girare i frame all'infinito." },

            // --- DA 46 A 60 ---
            { q: "LLDP è l'alternativa standard a:", a: ["CDP", "STP", "VTP", "DTP"], c: 0, f: "Link Layer Discovery Protocol è lo standard aperto." },
            { q: "In PVST+, la priorità totale è:", a: ["Priority + VLAN ID", "Priority + MAC", "Priority + IP", "Solo Priority"], c: 0, f: "Esempio: 32768 + 1 = 32769." },
            { q: "Se uno switch riceve un frame per un MAC ignoto:", a: ["Lo invia in flooding su tutte le porte della VLAN", "Lo scarta", "Lo invia al Root", "Chiede al DHCP"], c: 0, f: "Comportamento noto come Unicast Flooding." },
            { q: "Comando per disabilitare STP su una VLAN?", a: ["no spanning-tree vlan <id>", "spanning-tree disable", "disable stp", "vlan stp off"], c: 0, f: "Rimuove l'istanza STP per quella specifica VLAN." },
            { q: "Una 'Blocking Port' cosa fa?", a: ["Scarta i dati ma riceve BPDU", "Spegne la porta", "Invia dati", "Errore"], c: 0, f: "Rimane in ascolto pronta a intervenire se la topologia cambia." },
            { q: "RSTP genera BPDU proprie?", a: ["Sì, ogni switch le invia ogni Hello Time", "No, solo il Root", "Solo se c'è errore", "Solo i client"], c: 0, f: "RSTP non aspetta le BPDU dal Root per confermare la presenza." },
            { q: "In RSTP, tempo per dichiarare perso un vicino?", a: ["3 Hello Time (6 secondi)", "20 secondi", "50 secondi", "10 secondi"], c: 0, f: "Molto più veloce del Max Age classico." },
            { q: "Lo stato 'Listening' serve a:", a: ["Determinare la topologia tramite BPDU", "Imparare i MAC", "Inviare dati", "Spegnere"], c: 0, f: "Primo stadio dopo il Blocking." },
            { q: "PortFast può causare loop?", a: ["Sì, se collegata a un altro switch", "No", "Solo su Cisco", "Solo IPv6"], c: 0, f: "Per questo si usa con BPDU Guard." },
            { q: "Come si vede il MAC del Root Bridge?", a: ["show spanning-tree", "show root mac", "show version", "show mac-table"], c: 0, f: "L'output mostra il 'Root ID' completo." },
            { q: "Se le priorità sono tutte 32768:", a: ["Vince il MAC address più basso", "Vince il MAC più alto", "Nessuna elezione", "Si dividono il carico"], c: 0, f: "Il MAC è il criterio di spareggio." },
            { q: "RSTP 'Shared Port' indica:", a: ["Porta in Half-Duplex", "PortFast attivo", "Trunking", "EtherChannel"], c: 0, f: "Connessione a un dominio di collisione condiviso." },
            { q: "BackboneFast serve a:", a: ["Rilevare guasti ai link indiretti", "Velocizzare i PC", "Aumentare banda", "Routing"], c: 0, f: "Ottimizzazione per il core della rete." },
            { q: "In PVST+, ogni VLAN può avere un Root diverso?", a: ["Sì", "No", "Solo VLAN 1", "Solo VLAN dispari"], c: 0, f: "Permette di distribuire il traffico su link diversi." },
            { q: "Cosa succede con priority 0?", a: ["Lo switch vince quasi certamente l'elezione", "Ignora STP", "Rifiuta il comando", "Spegne le porte"], c: 0, f: "0 è il valore più forte possibile." }
        ]
    }
};
